version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: card_db
    environment:
      POSTGRES_DB: card_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d card_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: card_system_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/card_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_LIQUIBASE_ENABLED: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: