spring:
  application:
    name: card_system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/card_db
    username: admin
    password: admin
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/main-changelog.yml
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 300m
encryptor:
  secret-key: cf8e507cc98f6442
  salt: 8432c8f95fbcf775
