databaseChangeLog:
  - changeSet:
      id: v1-insert-values
      author: pavel puchkov
      changes:

        - insert:
            tableName: "roles"
            columns:
              - column:
                  name: name
                  value: "ROLE_USER"
        - insert:
            tableName: "roles"
            columns:
              - column:
                  name: name
                  value: "ROLE_ADMIN"
        - insert:
            tableName: users
            columns:
              - column:
                  name: name_surname
                  value: "user user"
              - column:
                  name: password
                  value: "$2a$12$iGqmys7QQ9AsNdJYXefJIOwwlW3BKnYTuAoGoXr0Ww//yk9YCWg.u"
              - column:
                  name: email
                  value: "user@mail.com"
        - insert:
            tableName: users
            columns:
              - column:
                  name: name_surname
                  value: "admin admin"
              - column:
                  name: password
                  value: "$2a$12$iGqmys7QQ9AsNdJYXefJIOwwlW3BKnYTuAoGoXr0Ww//yk9YCWg.u"
              - column:
                  name: email
                  value: "admin@mail.com"
        - insert:
            tableName: users_roles
            columns:
              - column:
                  name: user_id
                  value: "1"
              - column:
                  name: role_id
                  value: "1"
        - insert:
            tableName: users_roles
            columns:
              - column:
                  name: user_id
                  value: "2"
              - column:
                  name: role_id
                  value: "2"